version: '3.3'

services:
    web:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./env.dev
        depends_on:
            - db
    db:
        image: postgres:14.2-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mcdash
            - POSTGRES_PASSWORD=sC@7_zfaQXxEf553TPMB6!dP
            - POSTGRES_DB=mcdash

volumes:
    postgres_data:
